### ISSUE TITLE
config value issue

### ISSUE THREAD

**Issue by brusini** [aloneguid/config#1]
Weird thing, can't read a '0.0.0.0' value

e.g.

ControllerServerIP=0.0.0.0

Please fix.

**Comment by aloneguid** [comment]
Hi,
Could you please provide an example of how you are using it.

**Comment by brusini** [comment]
Sorry, was related to old framework issue.

**Comment by aloneguid** [comment]
No worries. Feel free to contact me, I'm keen to work on any new features or fix bugs.
