### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by ekalchev** [aloneguid/config#103]
Can I set/get properties on IMySettings interface from different threads. I can see IConfigStores are not thread safe but that is not problem for me. I can roll my own but I am not sure if InterfaceInterceptor, IoHandler and other classes in the core implementation are designed to be thread safe?

**Comment by ekalchev** [comment]
I'll be happy if I have a word on this. Thanks!

**Comment by HppZ** [comment]
so is it thread safe?
