### ISSUE TITLE
.net 6 support

### ISSUE THREAD

**Issue by MagicAndre1981** [aloneguid/config#120]
Btw, can you add .net 6 to TargetFrameworks and validate that the lib works fine with .net 6? [.net 6 entered RC stage](https://devblogs.microsoft.com/dotnet/announcing-net-6-release-candidate-1/) and is nearly finished.

**Comment by aloneguid** [comment]
It **should** work with .NET 6 as is, but adding explicit target is always good. Just need to figure out how to [install/build it](https://github.com/aloneguid/config/blob/master/.github/workflows/release.yml).

**Comment by aloneguid** [comment]
I think VS 2019 doesn't support .NET 6 as of yet. Personally I'm not ready for 2022 until [Visual Assist](https://www.wholetomato.com/) is compatible, but if you want it faster please try.

**Comment by MagicAndre1981** [comment]
> I think VS 2019 doesn't support .NET 6 as of yet. Personally I'm not ready for 2022 until [Visual Assist](https://www.wholetomato.com/) is compatible

The [addon was updated to support VS2022](https://www.wholetomato.com/features/whats-new), so you can now work with VS2022 preview 4.

> If you’re ready to move to Visual Studio 2022, so are we! In **2021.3 we introduced initial beta support for Preview 2 (and it’s worth using with Preview 3 as well** - see our blog detailing the changes.). This represents a big leap for us through the move to the 64-bit architecture. As the VS IDE becomes more stable over the next few previews and releases we hope to release more improvements to take advantage of the new architecture. Much of our work in this release was done to move existing features to VS 2022

I personally also can't update to VS2022 as I also miss some extensions, but for users who want to try to port their solutions to .net 6, a compatible version of your lib would be nice.
