### ISSUE TITLE
Saving settings..broken?

### ISSUE THREAD

**Issue by altmank** [aloneguid/config#122]
Tried on .NET 4.7.2 and .NET 5.0. Can't seem to get settings to save to the appsettings.json file. I assign the value then the setting doesn't get the value in memory and no data is written back to the json file. 

![image](https://user-images.githubusercontent.com/22986384/136468088-588f314d-b84e-4981-a897-77ff917cb2d9.png)

![image](https://user-images.githubusercontent.com/22986384/136468238-64ae6102-33e6-4b96-8078-3b441099a808.png)

**Comment by yegor-pelykh** [comment]
I have the same problem

**Comment by aloslider** [comment]
@altmank @yegor-pelykh You need to use "UseJson**File**()" method ([check this doc](https://github.com/aloneguid/config/blob/master/doc/Stores_JsonFile.md)) in orded to read and write to config file, but apparently it will probably throw you another exception, check #128

**Comment by aloneguid** [comment]
fixed in v5
