### ISSUE TITLE
[question] why json and yaml not included in library by default?

### ISSUE THREAD

**Issue by LeiYangGH** [aloneguid/config#123]
I'm just getting to try this lib, and I've successfuly used it to read/write .ini file. This is great.
```csharp
            IMySettings settings = new ConfigurationBuilder<IMySettings >()
               .UseIniFile<IMySettings >("cfg.ini")
               .Build();
```

But I don't see any similiar extension method for json and yaml, seems I need add more standalone packages.

So question is why json and yaml not supported by default? isn't json and yaml much more widely used?

**Comment by martin-braun** [comment]
I wonder myself as well. You have to install Config.Net.Json from NuGet to get it.

**Comment by LeiYangGH** [comment]
`UseJsonFile` enabled by `Config.Net.Json` is acceptable. but why there isn't `UseYamlFile` after installing `Config.Net.Yaml`?

**Comment by aloneguid** [comment]
JSON is now available by default.
Yaml isn't because it's an extra dependency.

**Comment by imclint21** [comment]
And why YAML does not write?

**Comment by HppZ** [comment]
@aloneguid `Config.Net.Json` is not available now?

**Comment by aloneguid** [comment]
It's part of core library as json is now naively supported by net so no extra dependency required.
