### ISSUE TITLE
UseJsonFile() throws System.IO.IOException

### ISSUE THREAD

**Issue by aloslider** [aloneguid/config#128]
### Issue overview
If I understand this correctly, this library gives you an option not to only read, but also write new values to provided configuration (correct me if I'm wrong), so I decided to try out an example from the [documentation](../blob/master/doc/Stores_JsonFile.md) using **UseJsonFile()**, but got System.IO.IOException when attempted to assign "New" value.

**Code:**
```cs
using Config.Net;

namespace MyApp
{
   class Program
   {
      static void Main(string[] args)
      {
         ISettings settings = new ConfigurationBuilder<ISettings>()
            .UseJsonFile("appsettings.json")
            .Build();

         Console.WriteLine(settings.Option);
         settings.Option = "New";
         Console.WriteLine(settings.Option);
         Console.ReadKey();
      }
   }

   public interface ISettings
   {
      public string Option { get; set; }
   }
}
```
appsettings.json that is in the same folder as executable:
```json
{
   "Option": "Old"
}
```

### What is causing the problem
The exception is being thrown in **Config.Net.Json.Stores.JsonFileConfigStore.WriteJsonFile()** line 165:
```File.Replace(tempPath, _pathName, backupPath);```

I checked [MSDN File.Replace method documentation](https://docs.microsoft.com/ru-ru/dotnet/api/system.io.file.replace?view=net-6.0) and recreatd the example, everything was fine. Then i changed this example, so it looks like **WriteJsonFile()** method: original file is being created within the Temp folder by calling **Path.GetTempFileName()**:
```cs
namespace MyApp
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                string originalFilePath = @"D:\test1.xml";            
                string fileToReplace = @"D:\test2.xml";
                string backUpOfFileToReplace = fileToReplace + ".backup";

                // Create temporary file
                string tempPath = Path.GetTempFileName();
                string allText = File.ReadAllText(originalFilePath);
                byte[] data = Encoding.UTF8.GetBytes(allText);
                using (FileStream tempFile = File.Create(tempPath, 4096, FileOptions.WriteThrough))
                    tempFile.Write(data, 0, data.Length);

                // Replace the file.
                File.Replace(tempPath, fileToReplace, backUpOfFileToReplace, false);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
        }
    }
}
```
As expected, System.IO.IOException was thrown. Every file does exist, so my only guess is that there's something wrong with ***.tmp** files that get created within the Temp folder: it does really contain new values to overwrite, but probably **File.Replace()** method can't do it with such temporary files. Also, if we create temporary file in some other directory, for say, project folder, then it works ok.

### StackTrace
```
at System.IO.FileSystem.ReplaceFile(String sourceFullPath, String destFullPath, String destBackupFullPath, Boolean ignoreMetadataErrors)
at System.IO.File.Replace(String sourceFileName, String destinationFileName, String destinationBackupFileName, Boolean ignoreMetadataErrors)
 at System.IO.File.Replace(String sourceFileName, String destinationFileName, String destinationBackupFileName)
 at ConfigurationTests.Program.Main(String[] args) in D:\Visual Studio Stuff\repos\ConsoleTests\MyApp\Program.cs:line 22
```

**Comment by aloslider** [comment]
I'm totally blind: on MSDN it says that File.Replace will throw an exception if source and destination files are on the different volumes.

**Comment by vgdh** [comment]
same issue

**Comment by vgdh** [comment]
in version 5 "json write" feature work only on read
The write feature is disable in hardcode

**Comment by jeffward01** [comment]
> in version 5 "json write" feature work only on read The write feature is disable in hardcode

* Are the source and destinations on different volumes?
* What are you trying to accomplish?
* What is the name of the Json File? You can also use `.UseJsonConfig()` if your config filename is `appsettings.json`

**Comment by vgdh** [comment]
> > in version 5 "json write" feature work only on read The write feature is disable in hardcode
> 
> * Are the source and destinations on different volumes?
> * What are you trying to accomplish?
> * What is the name of the Json File? You can also use `.UseJsonConfig()` if your config filename is `appsettings.json`

I mean that this code will not work correctly.
`         ISettings settings = new ConfigurationBuilder<ISettings>()
            .UseJsonFile("appsettings.json")
            .Build();

         Console.WriteLine(settings.Option);
         settings.Option = "New";
         Console.WriteLine(settings.Option);
         Console.ReadKey();`

**Comment by jeffward01** [comment]
Why do you use `.UseJsonFile(<string>)`?
````csharp
ISettings settings = new ConfigurationBuilder<ISettings>()
            .UseJsonFile("appsettings.json")
            .Build();
````

You should use: 
`UseJsonConfig()` as I mentioned earlier. It is the more updated method (I believe I am correct on this @aloneguid please correct me if i am wrong). and `UseJsonConfig()` expects a file with the name `appsettings.json` so you do not need to include `appsettings.json`

**Comment by vgdh** [comment]
Thank you.
On version 5.1.2 it works fine!
👍
