### ISSUE TITLE
[Not a Bug] - Many new updates <3 - The WIKI is broken, can I help fix it?

### ISSUE THREAD

**Issue by jeffward01** [aloneguid/config#141]
Hello!

I noticed that it seems you merged `Config.Net.Json` with `Config.Net` - I think that was a good choice if I am correct because often times `.json` files are used in config, its very common.

I noticed nearly all of the Wiki page URL's are broken. I suspect that its because the wiki page urls changed.

I just wanted to ask:

1. if you need help updating the URL's in the Wiki?
2. What changes were made in this latest `v5` release?
3. Where can I find the missing Wiki pages so I can fix the URL's, such as 'Build a custom parser'?

Thanks for an AWESOME library!!!!! I use it daily, its excellent!!! <3

**Comment by jeffward01** [comment]
I just realized I had to change:

`UseJsonFile` to `UseJsonConfig`  - in order to access settings from `appsettings.json`

**Comment by aloneguid** [comment]
oops all the links should be valid now, refactoring gone wrong :)
