### ISSUE TITLE
Config.Net 5.1.0 searches for an incorrect 'System.Text.Json' version.

### ISSUE THREAD

**Issue by Robin-Wils** [aloneguid/config#142]
Config.Net 5.1.0 searches for an incorrect 'System.Text.Json' version. Config.Net installed 'System.Text.Json' 6.0.5, but 6.0.0 seems to be needed if I read the error message correctly.

```
Exception thrown: 'System.IO.FileLoadException' in Config.Net.dll
An exception of type 'System.IO.FileLoadException' occurred in Config.Net.dll but was not handled in user code
Could not load file or assembly 'System.Text.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

My project uses framework net461, with LangVersion 7.3.

**Comment by Robin-Wils** [comment]
My temporary workaround is to downgrade, and include Config.Net.Json. Even though it is deprecated.
```
<PackageReference Include="Config.Net" Version="5.0.3" />
<PackageReference Include="Config.Net.Json" Version="4.19.0" />
```

**Comment by aloneguid** [comment]
I think 6.0.0.0 is assembly version, it's still the same in 6.0.5. Can you try to explicitly reference System.Text.Json 5.0.3 from nuget? Unfortunately I'm not able to validate with .net 4.6.1 here.

**Comment by Robin-Wils** [comment]
I haven't managed to do that. It seems to prefer to select the version of this library over the now installed nuget package one.

**Comment by aloneguid** [comment]
Any chance you can attach a reproducible solution here?

**Comment by aloneguid** [comment]
I have now pushed tests targeting .NET 4.6.1 specifically, they have no issues so far.

**Comment by Robin-Wils** [comment]
I just made a demoproject, which seems to work. There must be something else that I did wrong in that other solution. It is odd as the previous version of Config.Net works.

**Comment by Robin-Wils** [comment]
I seem to be one step further when I use the latest version. Now it can't find 'System.Runtime.CompilerServices.Unsafe'. I don't think that I have changed anything related in the meantime.
![image](https://user-images.githubusercontent.com/5617025/185936482-2ed3dc01-f966-4eb5-af40-7a4bbee3d825.png)

**Comment by aloneguid** [comment]
Feel free to investigate and raise a PR.

**Comment by Robin-Wils** [comment]
I just figured it out a way to reproduce it. Once I set OutputType to `Library` instead of `Exe` it happens. Note that I want it to be a library, as I include it in different projects of the solution.
![image](https://user-images.githubusercontent.com/5617025/185938514-0080efd3-6770-4b48-985e-ae6f922c40b2.png)
