### ISSUE TITLE
Exception if initializing a JSON file in a directory that does not exist.

### ISSUE THREAD

**Issue by ykarpeev** [aloneguid/config#145]
Hello, I notice that if you initialize a JSON store in a directory which doesn't exist you'll get an exception once you try to set a setting.

The issue is at   File.WriteAllText(_pathName, js) which tries to write to a folder that isn't there.

I have a solution locally to create the directory first if it does not exist. 

Here is a change to JsonConfigFileStore to resolve it for me, if that is the appropriate place to do that.

```
       string js = _j.ToJsonString(new JsonSerializerOptions { WriteIndented = true });

         FileInfo file = new FileInfo(_pathName);

         if (file is not null)
         {
            if (file.Directory is not null)
            {
               file.Directory.Create();
            }
         }

         File.WriteAllText(_pathName, js);

```

Here is a small unit test I added to experiment.

```
     [Fact]
      public void TestCreatingFileInMissingFolder()
      {
         _path = Path.Combine("C:\\temp", "TestData", "sample.json");

         if (Directory.Exists(_path))
         {
            Directory.Delete(_path);
         }

         string key = "One.Two.Three";

         _store = new JsonConfigStore(_path, true);
         _store.Write(key, "111");

         Assert.Equal("111", _store.Read(key));

         Assert.True(File.Exists(_path));
      }

```

**Comment by Lilyliu123** [comment]
We are encountering the same issue. Has this been looked into?

**Comment by aloneguid** [comment]
Not to my knowledge. Feel free to work on it and raise a PR.
