### ISSUE TITLE
Default name with read-only properties

### ISSUE THREAD

**Issue by FireNero** [aloneguid/config#15]
In current implementation, if I use readonly property, values are writing and then reading properly but file storage file looks awkward. For example ini storage with the following code: 
``` csharp 
    public class AllSettings : SettingsContainer
    {
        public Option<string> AuthClientId { get; } = new Option<string>("Id");

        public Option<string> AuthClientSecret { get; } = new Option<string>("Secret");

        protected override void OnConfigure(IConfigConfiguration configuration)
        {
            configuration.UseIniFile(@"path_to_config.ini");
        }
    }
```
Produces the following file:
```
<AuthClientId>k__BackingField=Id
<AuthClientSecret>k__BackingField=Secret
```

Similar thing happens for JSON storage:
``` json
{
    "<AuthClientId>k__BackingField":"Id",
    "<AuthClientSecret>k__BackingField":"Secret"
}
```

If I specify option name file is filling up correctly. It would be great to populate default name from option property correctly as well. 

Current workaround for this issue is to create property like this: 
``` csharp
public Option<string> AuthClientId { get; } = new Option<string>(nameof(AuthClientId), "TestId");
```

**Comment by aloneguid** [comment]
You're right, this is happening because config only looks at members and not properties. If you declare it like that C# generates a backing field with this name `<PropertyName>_BackindField` which theoretically should be skipped as they are private but there is a bug which doesn't. If you declare

```csharp
public Option<string> AuthClientId { get; } = new Option<string>("Id");
```
as

```csharp
public readonly Option<string> AuthClientId = new Option<string>("Id");
```

it will work as expected. Why is this syntax not acceptable?

**Comment by FireNero** [comment]
The main benefit of using property in my use case is that I can delegate options to another class like this:
``` csharp
private OptionsProvider _someProvider = new OptionsProvider();
public Option<string> AuthClientId => _someProvider.ClientIdOption;
public Option<int> SomeValue => _someProvider.SomeValueOption;
```
And then if I change inner provider logic I will need to update only AuthClientId getter but not all code that depends on it. Also, this allows to inject provider into class constructor and conditionally resolve the instance. So it's just about flexibility.

I haven't checked your implementation yet so I don't know if it's difficult to implement. If it is, then I can stick with my workaround as it is not the use case that happens often.

**Comment by FireNero** [comment]
I've thought about it again and found my mistake. I've provided an example with computed property instead of readonly. And now I think that there is no real difference between using readonly field or readonly property in current settings context.
