### ISSUE TITLE
Nested options support

### ISSUE THREAD

**Issue by FireNero** [aloneguid/config#16]
I want to store a lot of settings in the single file. In this case, SettingsContainer becomes a mess of huge amount of properties which is hard to maintain and use.
It would be nice to have an opportunity to create nested options. Something like this:
``` csharp
public class NestedConfig
    {
        public Option<string> UserId { get; } = new Option<string>(nameof(UserId), "UserId");
        public Option<string> UserName { get; } = new Option<string>(nameof(UserName), "UserName");
    }

public class AllSettings : SettingsContainer
    {
        public Option<string> AuthClientId { get; } = new Option<string>(nameof(AuthClientId), "TestId");

        public Option<string> AuthClientSecret { get; } = new Option<string>("Secret");

        public Option<int> Quantity { get; } = new Option<int>();

        public NestedConfig Nested { get; } = new NestedConfig();

        protected override void OnConfigure(IConfigConfiguration configuration)
        {
            configuration.UseJsonConfig(@"path_to_config.json");
        }
    }
```

Then it could be accessed in code like this:
``` csharp
var settings = new AllSettings();
string userId = settings.Nested.UserId;
settings.Nested.UserId.Write("test");
```

This will help to work with a lot of settings stored in single file and avoid naming conflicts.

**Comment by aloneguid** [comment]
I'm missing this functionality too, and was thinking about it for some time. The reason I didn't implement it is I wanted to come up with a beautiful syntax and avoid declaring another class for nested options i.e. something like

```csharp
public class AllSettings: SettingsContainer
{
   // first level declarations

  something something
 {
    //second level declarations
 }
}
```

but I couldn't find a way to express it in C# magically. Although thinking about it now your suggestion is good too, for example you may want to have a nested definition and share it between containers. Should definitely do this.

**Comment by ravensorb** [comment]
What about leveraging some ideas from this library?  https://github.com/Dynalon/JsonConfig

**Comment by aloneguid** [comment]
@ravensorb i don't see a point in that library, Json.net does the same out of the box. Also dynamics for configuration is a terrible idea as it's duck typing instead of strong typing which is what I'm trying to avoid.

**Comment by ravensorb** [comment]
the idea was around the syntax :) Not the specific implementation.
