### ISSUE TITLE
Read option API

### ISSUE THREAD

**Issue by FireNero** [aloneguid/config#17]
Currently to read actual value from the option I need to write it in the one of the following ways:
``` csharp
var settings = new AllSettings();
int value1 = settings.IntegerOption;
var value2 = (int)settings.IntegerOption;
```
I don't like to write type or use implicit cast because I need to know actual setting type when I writing the code. And it slows down code typing speed much.

It would be useful to have a method or property to get actual value from option. Something like this:
``` csharp
var settings = new AllSettings();
var value = settings.IntegerOption.Value;
```
or
``` csharp
var settings = new AllSettings();
var value = settings.IntegerOption.GetValue();
```

**Comment by aloneguid** [comment]
Agree, it would be useful. You can now use `settings.MyOption.Value` getter which is of strong type. Should be on NuGet in a few minutes.
