### ISSUE TITLE
Allow relative file paths.

### ISSUE THREAD

**Issue by FireNero** [aloneguid/config#18]
Add possibility to pass relative file path into file storages like INI or JSON. This may be useful in some situations.

**Comment by jsobell** [comment]
@aloneguid Ivan, I think these are now covered in the #29, but I realised I haven't covered YAML, so I'll do that tomorrow and create another PR.
Relative location is covered by the Store Order tests as they load the JSON files from a relative location.

**Comment by jsobell** [comment]
Hi Ivan, I think you can close this now. YAML was covered by #31
