### ISSUE TITLE
Support CommandLine nakedness

### ISSUE THREAD

**Issue by AndyCross** [aloneguid/config#20]
## Command Line Usability

If I want to supply friendly cmdline apps I might want to allow the user to omit the key part of the keyvalue pair. As an example, rather than

```parq InputFilePath=/path/to/file```

I might want to let my users simply enter:

```parq /path/to/file```

using config.NET, I am forced to force my users to enter the full key value pair, rather than defaulting the key to populate by ordinal. 

## Sample post-solution code

This would be rocking:

```csharp
   class AppSettings : SettingsContainer
   {
      **[DefaultOrdinal(0)]** //awesomeness here
      public readonly Option<string> InputFilePath = new Option<string>();
```

**Comment by aloneguid** [comment]
@AndyCross it's implemented now in this form, will it work in your case? https://github.com/aloneguid/config/blob/master/doc/Stores_CommandLine.md
