### ISSUE TITLE
DateTime parser issue regarding timezone

### ISSUE THREAD

**Issue by HarpunDK** [aloneguid/config#21]
Hi Config.net

I am writing because I have detected an issue with the default datetimeparser. 
When writing datetime to file, the <value>.ToString("u") is used. The value is stored correct.

Upon reading the stored datetime value as string, the time is not correct. Time is not correct due to timezone (z) in the stored string. 

Solution could be:
A) <value>.ToUniversalTime.ToString("u")
B) Allow supported datatypes to be replaced. Lets say I have a custom DateTimeParser I want to replace the current implementation, "RemoveParser" could come in handy. 

**Sample:** 
"Original value": 2017-07-13 22:28:52
Stored value: 2017-07-13 22:28:52Z
Read value: 2017-07-14 00:28:52

Let me know if you need further information.

**Comment by HarpunDK** [comment]
Hi 

I tried to inject/add a customer DateTime parser on the wrong branch. Adding a parser with existing type-support "OnConfigure" will overrule previous added. 

Please consider Option A then, if a better solution exists. This issue should be global I think and to my local solution. Let me know if I can assist.
Thank you for a great framework.

**Comment by aloneguid** [comment]
@HarpunDK thanks for reporting this, it's a bug indeed. The fix should be on NuGet in a minute or so :)

**Comment by HarpunDK** [comment]
Works like a charm. Thank you for your quick response.
