### ISSUE TITLE
Allow specifying derived classes in ConfigurationBuilder

### ISSUE THREAD

**Issue by aloneguid** [aloneguid/config#35]
> I think you need to use new ConfigurationBuilder<ServerSettings>(), rather than the interface. I suppose you have to decide whether it's correct to dynamically create each property, or have a configuration class. A class is more flexible, as the user can add functions such derived properties or license key decryption stuff.

**Comment by ElijahReva** [comment]
For instance, is there any way to add `INotifyPropertyChanged` to option object other than using the additional proxy object? I'm using 4.1.0 Config.Net.

**Comment by aloneguid** [comment]
@ElijahReva not exactly following you.
