### ISSUE TITLE
DoubleParser does not respect locale Settings

### ISSUE THREAD

**Issue by michaelrall** [aloneguid/config#40]
When running the UnitTests on a Windows-PC with german locale settings, the DoubleParser-Tests fail.

# Reason
On Parsing the String-Values, there is no locale set, so the system locale is used. Due to the fact that the test-data has a point as decimal separator (for german locale a comma would be correct), the parser results in a wrong number (e.g. "1,797693" results in double value "1797693").

# Problem
Changing the test-data to a german locale format with comma, will result in correct parsing the value, but the test fails anyway, because the method TypeParser.ToRawString(...) uses an invariant culture, so "1,797693" <> "1.797693".

## Possible Solution 1
Always use a defined locale (invariant or en-EN, or whatever) and document that. Hard fail on other formats.

## Possible Solution 2
Let the parser determine the correct locale (e.g. scanning for points and commas) -> can be tricky for special locales -> "magic" can introduce hard to find bugs.

## Possible Solution 3
Passing an optional argument to the Parser-Contructor to set the locale to use for TryParse() and toRawString() -> would be always correct, but introduces complexity for the library-user.

**Comment by aloneguid** [comment]
As awful as it may sound I'm keen to use specific locale to parse doubles. This will ensure that if another service reads the same config but uses different culture it's still readable.

**Comment by michaelrall** [comment]
I don't thinks thats awful at all. In my opinion it's much better to have a defined and documented behavior than an excpected or even worse a variable/dependant behavior. In addition in this case you would have no disadvantages because the information quality will stay the same regardless which locale you will chosse finally.

**Comment by aloneguid** [comment]
Thanks just putting in a fix for all types. Still testing that nothing breaks)
