### ISSUE TITLE
Registration of Custom Parser

### ISSUE THREAD

**Issue by Good-man** [aloneguid/config#47]
I have implemented a custom parser, but I do not see how to register it.  I do not see a ContainerConfiguration in version 4.5.0.76.  Was it removed?  Was it added to a later version?

**Comment by aloneguid** [comment]
@Good-man thanks for pointing this out, it was left out for some strange reason in 4.x but was available in 3.x and the docs are also still for 3.x. I'm working on it right now.

**Comment by aloneguid** [comment]
@Good-man just release v4.6 which fixes this issue, and updated docs at: https://github.com/aloneguid/config/blob/master/doc/CustomParsers.md

**Comment by Good-man** [comment]
Thank you @aloneguid!  However, now .UseJsonFile() is missing.  Did you remove this method?

**Comment by aloneguid** [comment]
my bad @Good-man, sine 4.5.x json support is in a separate nuget package - https://www.nuget.org/packages/Config.Net.Json to minimise external dependencies of the core library.

**Comment by Good-man** [comment]
That did the trick!  Thank you!
