### ISSUE TITLE
Mono debugger crashes when inspecting an interface instance in the debugger

### ISSUE THREAD

**Issue by Nihlus** [aloneguid/config#49]
I'm currently using Rider to develop Mono-target `net462` applications, and when attempting to inspect an interface instance, the debugger crashes. I'm unsure what the cause is, and I haven't been able to narrow down a cause in the interface itself. Even a simple string-typed single-property interfaces causes this behaviour.

I'm using the INI file store. I've attached the crash log from [Mono][1].

This is under Mono 5.4.1.7, and Linux Mint 18.3. I'm using Rider, and I have the .NET Core SDK installed.

[1]: https://gist.github.com/Nihlus/d3274a9cce07728c3b36ce2da8082492

**Comment by aloneguid** [comment]
@Nihlus I'm not convinced config.net is causing this.

**Comment by Nihlus** [comment]
It's very specific - as soon as an instance produced by config.net comes into view in the debugger, the runtime crashes. Is the library doing anything in particular with debugger displays or its ToString methods?

**Comment by aloneguid** [comment]
@Nihlus not really, it's doing a fair bit of reflection, but nothing unsafe etc. I'm afraid if you're using Mono you'll have to investigate it yourself, this runtime is a bit deprecated.

**Comment by Nihlus** [comment]
Mono is far from deprecated. .NET Core does not support any form of UI frameworks, and Mono has greater API coverage - not to mention that it supports more platforms. I'll pass the crash on to Mono's bugzilla and see if I get any input there.

**Comment by TheBlackCentipede** [comment]
@Nihlus I could argue that CoreCLR/.Net Core are basically broken in comparison to Mono, so Mono is far from being deprecated. And internally, CoreCLR is written in C++ while Mono is written in C, so it's a lot easier than you think to access CLR internals in Mono than CoreCLR which enables some extreme optimizations to be made.

**Comment by aloneguid** [comment]
@Nihlus @TheBlackCentipede  I'm happy for you guys to fix Mono issues, I just don't have enough knowledge of this runtime. Is it used only in Unity 3D these days?

**Comment by Nihlus** [comment]
This issue was fixed in the Mono 5.8 release. Updating to the beta release candidate is a good workaround for now.

As for Mono's usage, it's used for just about every desktop application with a UI on systems that aren't Windows. It's for far more than just unity or a stray application here and there.

**Comment by TheBlackCentipede** [comment]
@aloneguid It is used by Unity 3D, but it's also used for various other projects that may not be as obvious such as applications that use GTK or being used to make Windows Compositing software and so forth. When using Mono, it have pretty solid CLR API that you can internally register some internal calls that are written in C/C++ to handle the marshaling manually rather than leaving it to Mono CLR to create a P/Invoke stub around native functions.

[Mono Embedded API Documentation](http://www.mono-project.com/docs/advanced/embedding/)
