### ISSUE TITLE
Custom Type Parser

### ISSUE THREAD

**Issue by flx5** [aloneguid/config#5]
Hello,

The readme mentions the ability to create custom type parsers by implementing ITypeParser.
Sadly I can't figure out a way to actually register the parser.
By looking at the code it doesn't seem like that is possible at all.

**Comment by aloneguid** [comment]
It's on NuGet now, I've also added unit tests for it. Please try.

**Comment by flx5** [comment]
Thank you, works perfectly. Keep up the good work!
