### ISSUE TITLE
nuget

### ISSUE THREAD

**Issue by ghost1372** [aloneguid/config#51]
is there any nuget package?

**Comment by aloneguid** [comment]
Of course, it's on the front page, here is a link https://www.nuget.org/packages/Config.Net

**Comment by ghost1372** [comment]
tnx please update readme.md and put nuget link

**Comment by aloneguid** [comment]
@ghost1372 it is there and was there all the time ;) Next to the title.

**Comment by ghost1372** [comment]
Yes its there, i didnt see it, why i cant install it on NetFramwork 4.5? installed only on netframwokr 6

**Comment by aloneguid** [comment]
It supports as a minimum:
- .NET Framework 4.5.2
- .NET Standard 1.4

**Comment by ghost1372** [comment]
if i use net 4.5.2 with this lib and in my client netframwork 4.5 installed, my app run correctly?

**Comment by aloneguid** [comment]
@ghost1372  seems right to me, do you get any error when installing nuget package?

**Comment by ghost1372** [comment]
in 4.5 i get error, now i installed on 4.6 and its awsome 👍 
i will test on 4.5.2
