### ISSUE TITLE
Support group items and array style

### ISSUE THREAD

**Issue by ghost1372** [aloneguid/config#52]
I do not know if such a feature is available in this library, but it would be better if it were.
Data grouping
![s](https://user-images.githubusercontent.com/9213496/35587684-c189edfa-0613-11e8-85a0-268dacfb8e15.png)
and in json
![default](https://user-images.githubusercontent.com/9213496/35587890-4e804a10-0614-11e8-80fa-430485ffc35d.png)

I used the array, but the result is not interesting
in json:
![zz](https://user-images.githubusercontent.com/9213496/35588028-b32739f6-0614-11e8-81fb-a37275fef399.png)
in ini:
![xxx](https://user-images.githubusercontent.com/9213496/35588074-d001124a-0614-11e8-9554-4dea0d2c6d09.png)

This will be better:
![1](https://user-images.githubusercontent.com/9213496/35588188-1a36e452-0615-11e8-9db4-27adbf13ea42.png)

and json:
![2](https://user-images.githubusercontent.com/9213496/35588292-6c0afebc-0615-11e8-819b-c43e5e4762cb.png)

**Comment by aloneguid** [comment]
I know the pain, there is an issue open already for this #46 for JSON provider.

**Comment by aloneguid** [comment]
@ghost1372 regarding .ini files, the space separated format is much better, you'll see that when working more with arrays in .ini. Introducing brackets and commas, or just about anything, will add more complexity and force you to do special escaping which is not required at the moment.

**Comment by aloneguid** [comment]
closing this as collections are now supported!
