### ISSUE TITLE
DateTime loss of precision, miliseconds are lost in "translation"

### ISSUE THREAD

**Issue by HarpunDK** [aloneguid/config#56]
Hi Config.net

First of all, it's been a while since I've last used this package - NICE WORK on the doc and in the usage of Interfaces - very pleased with that.

I have an issue with datetime and miliseconds getting lost. 
The "u" in DateTime.ToString skips miliseconds.

I've tried adding a TypeParser supporting DateTime - tried to overwrite the existing TypeParser in Core. My own parser is used in writing but not in "reading". 

I remember earlier it was possible to overwrite a TypeParser. 
Lets say I would like to use "O" instead of "u" - is this possible? I know it will fault in backward compatibility - is there possible to overwrite the current format?

Let me know if I should clearify things a bit.

**Comment by aloneguid** [comment]
Thanks @HarpunDK for kind comments, appreciate it ;) You can overwrite built-in parsers, I've just created a test. This can be set during configuration stage like this:

```csharp
         ICustomTypes config = new ConfigurationBuilder<ICustomTypes>()
            .UseConfigStore(_store)
            .UseTypeParser(new MyParser())
            .Build();
```

The last added parser for a type always wins in terms of priorities, therefore if `MyParser` implements `DateTime` parsing it will be used for both reading and writing.
