### ISSUE TITLE
How manage custom sections with in AppConfig?

### ISSUE THREAD

**Issue by gabrielizalo** [aloneguid/config#64]
Hello,

Having an app.config like this one:
```
<configuration>
  <configSections>
    <section name="CategorizerSettings" type="???" />
  </configSections>
  <CategorizerSettings>
    <category Text="Google" Folder="GoogleFolder" />
    <category Text="Yahoo" Folder="YahooFolder" />
  </CategorizerSettings>
  <appSettings>
    <add key="SourceFolder" value="MySourceFolder" />
  </appSettings>
  ...
```
I can read easly `app key` **SourceFolder**, but how I can read the categories into `CategorizerSettings` section?

Thanks

**Comment by aloneguid** [comment]
This is not supported at the moment, however you can extend existing config store to add this easily as it depends on standard ConfigurationManager.

**Comment by aloneguid** [comment]
they are all supported since version 4.12, see https://github.com/aloneguid/config/blob/master/doc/Stores_AppConfig.md
