### ISSUE TITLE
Add DataProtectionScope to the OptionAttribute

### ISSUE THREAD

**Issue by maelgrove** [aloneguid/config#68]
This change would introduce some additional optional step after parsing/converting the values which would allow to encrypt/decrypt the configuration values. There must be some way to determine whether a `IConfigStore` actually supports the flag, since having a user entering an encrypted string into e.g. the command line sure would make no sense.

**Comment by aloneguid** [comment]
You could probably create an implementation of `IConfigStore` which takes another IConfigStore as a dependency and proxies the calls, at the same time encrypting/decrypting them? So they can be chained together. 

Of course the library can provide a convenient way to configure chaining.
