### ISSUE TITLE
Configuration reader for JSON files

### ISSUE THREAD

**Issue by aloneguid** [aloneguid/config#7]

**Comment by FireNero** [comment]
Hi! I'd like to use your library in our project but we definitely need writable JSON storage. Have you started to implement it already? If no, I will implement it myself and can create a pull request for it. What do you think about it?

**Comment by aloneguid** [comment]
Hi @FireNero please go ahead, I haven't started on this yet.

**Comment by FireNero** [comment]
@aloneguid Do you allow referencing 3rd party library for this task? I want to use Newtonsoft.Json here.

**Comment by aloneguid** [comment]
@FireNero Newtonsoft.Json is OK, it's used in many projects.
