### ISSUE TITLE
Configuration reader for Git repo

### ISSUE THREAD

**Issue by cosmocracy** [aloneguid/config#8]
To further separate configuration from the application bits (and their deployment), consider implementing a reader that would allow for the backing configuration data to be housed in a Git repository.  

Complicating Factors:
* Use local/installed Git client or pull in a library (e.g., LibGit2Sharp)?
* Need to address authentication (e.g., SSH keys) and other Git client issues
* May wish to introduce the concept of application "profiles" (e.g., folder tree in the Git repo) so that the app can be deployed more than once (using different config content from the Git repo)

**Comment by aloneguid** [comment]
@cosmocracy what would be the use case for storing configuration in Git? Are you expecting something like .ini files in a git branch?
