### ISSUE TITLE
Remove 'IsVisible' check from configuration builder

### ISSUE THREAD

**Issue by maelgrove** [aloneguid/config#80]
The current configuration contract verification checks in the `ConfigurationBuilder` expect the interface to be visible from the outside of the assembly. This kinda makes sense as Castle.Core needs to be able to reflect the type in order to create a proxy, but being forced to expose a possibly internal contract isn't that nice either.

Suggestion:
Remove the `.IsVisible` check and state in the documentation that if internal types want to be used, users should declare `[assembly: InternalsVisibleTo ("DynamicProxyGenAssembly2")]` within their assembly.

**Comment by aloneguid** [comment]
Makes perfect sense. Unless someone thinks of a better idea how to make it possible to consume private types.

**Comment by RyanLilla** [comment]
I can take this on if it is still available!

Just to make sure I am understanding the requests correctly:

- We want to remove the .IsVisible check within the ConfigurationBuilder constructor located at: 
        config/src/Config.Net/ConfigurationBuilder.cs

- State in the README.md that users will have to add the above declaration in their assembly if internal types want to be used

Does this sound right?

**Comment by aloneguid** [comment]
Please go ahead, no one started working on it yet to my knowledge.
