### ISSUE TITLE
Do you plan to support ConfigurationManager.ConnectionString?

### ISSUE THREAD

**Issue by dpaissan** [aloneguid/config#81]
Hello, I am wondering why only `ConfigurationManager.AppSettings` is involved in this library and the `ConfigurationManager.ConnectionString` is not accessible from anywhere.

Do you plan to support `ConfigurationManager.ConnectionString`?

**Comment by bluebaroncanada** [comment]
I guess not ...

**Comment by aloneguid** [comment]
It's already supported, the docs have been updated
