### ISSUE TITLE
Usage of default value

### ISSUE THREAD

**Issue by sobotkami** [aloneguid/config#85]
Hello,

if I provide the default values there is no option to get "notification" that the default value was provided instead of the null value.

Use case:
1) The user starts the App
2) App loads the config file
3) Some key is missing (check for null)
4) App should inform the user that the key is missing and provide a solution to this problem that the default value will be used

This is not possible now because I get in step 3 instead of the null the default value without the information, that the default value was used.

**Comment by aloneguid** [comment]
Is it important for the user that the key is missing? Unless you are wring an application to edit configuration files I'm not sure this is valid. The idea is your application shouldn't care where the value comes from as what user gets may not be what's in a specific file, especially when there are multiple configuration sources configured.

Alternatively, you can create an extension method (having it here in a PR would be wonderful) what checks if a value is a default value for specific member.

**Comment by sobotkami** [comment]
This is actually exactly my the case. I have an Installer, an App and a library with the settings interface. Both of the Installer and App uses the same settings interface from the library. So have I all the pieces of information in one place. 

Maybe the option to say no matter if the default value is set (there is a default value in the annotation) or not, don't load the default values?
