### ISSUE TITLE
Overriding Or fallback support

### ISSUE THREAD

**Issue by feitzi** [aloneguid/config#88]
I am currently evaluating some configuration libraries. This library looks pretty good to me :)
But I am wondering why you do not support fallback scenarios. 
I want to use a configuration structure like this:
* config.default.json
* config.prod.json
* config.server1.json

server1.json overrides prod.json and prod.json overrides default.json. Naturally, this works only if you are in prod environment and on a host with name server1

Does config.net support something like this?

**Comment by aloneguid** [comment]
Thanks @feitzi for a good feedback (contribution will be even better :) ). Yes you can totally do that today with config.net. For instance you can do something like this:

```csharp
IMySettings settings = new ConfigurationBuilder<IMySettings>()
   .UseJsonFile("config.default.json")
   .UseJsonFile("config.prod.json") //replace with config.etc.json
   .Build();
```

and so on. It will try to read the values in the order of declaration.

**Comment by golavr** [comment]
@feitzi you can use the `appsettings.json` similar to ASP.NET configuration. 
Handling `appsettings.json` with environment override file `appsettings.{Environment}.json` based on "APP_ENV" environment variable.

See [Mapping to appsettings.json file](https://github.com/aloneguid/config/blob/master/doc/Stores_JsonFile.md#mapping-to-appsettingsjson-file) for more information.
