### ISSUE TITLE
Add Azure App Configuration support

### ISSUE THREAD

**Issue by aloneguid** [aloneguid/config#91]
https://docs.microsoft.com/en-gb/azure/azure-app-configuration/

**Comment by PockyBum522** [comment]
Is this related to 

![image](https://user-images.githubusercontent.com/1970959/159513050-c7d65e27-2dd3-4943-b661-48eebdd1f36c.png)
 
all these failing?

**Comment by PockyBum522** [comment]
https://github.com/aloneguid/config/pull/137 

That PR is related to those tests misbehaving. If it's unnecessary because of something I don't understand, just trash it.

**Comment by aloneguid** [comment]
merged in v5
