### ISSUE TITLE
Versioninfo in csprok doesn't match nuget version of your lib

### ISSUE THREAD

**Issue by MagicAndre1981** [aloneguid/config#94]
When I compiled the lib to debug the code (because the [lib doesn't support source link](https://github.com/aloneguid/config/issues/93)), I noticed the the version is [4.7.3](https://github.com/aloneguid/config/blob/master/src/Config.Net/Config.Net.csproj#L22) (Config.Net.4.7.3.nupkg) and not [4.13.7](https://www.nuget.org/packages/Config.Net/4.13.7).

So update the version in code when releasing a new version to nuget.

**Comment by aloneguid** [comment]
The version is generated by a build pipeline, it overwrites the numbers so it's irrelevant what's the value there.
