### ISSUE TITLE
Custom property name resolution without using OptionAttribute

### ISSUE THREAD

**Issue by aviadmini** [aloneguid/config#95]
Something like 
```
interface IStoreNameResolver {
    string ResolveName(PropertyInfo info);
    string ResolveName(MethodInfo info);
}
```
Implementation would provide a store name for property/method, or null in which case Config.net would default to current logic (Option attribute, or name of property/method)

**Comment by aloneguid** [comment]
What's the use case? By the way, have you tried using Get/Set **methods** that can be declared on the interface?
