### ISSUE TITLE
Support of DefaultValueAttribute

### ISSUE THREAD

**Issue by LaurentMinot** [aloneguid/config#98]
Hello,

Would it be possible to support  System.ComponentModel.DefaultValueAttribute additionally to OptionAttribute(DefaultValue= )?
In my case I don't want to propagate Config.net in all my code (for instances some plugins), and that would be a good solution.

Thanks,
Laurent

**Comment by aloneguid** [comment]
I think it's a great idea! Are you happy to raise a PR for this or want me to implement it?

**Comment by LaurentMinot** [comment]
Well it's for my job, so I think I can deal with this one :-) 
I'll create A PR next week
